(() => {
const el=id=>document.getElementById(id);let workspace,dirty=false,loading=false,loadedName=null;
const input=(name,text)=>({type:'field_input',name,text}),num=(name,value,min=0,max=86400,precision)=>({type:'field_number',name,value,min,max,...(precision?{precision}: {})});
const menus={buttons:[],screens:[],numbers:[],programs:[]};
function menu(kind){return menus[kind].length?menus[kind]:[['Create a '+kind.slice(0,-1)+' template first','__missing__']];}
function dropdown(name,kind){return {type:'field_dropdown',name,options:[['Loading…','__missing__']]};}
for(const kind of Object.keys(menus))Blockly.Extensions.register('az_'+kind+'_menu',function(){const field=this.getField(kind==='numbers'?'SOURCE':'NAME');field.setOptions(()=>menu(kind));});
const value=(name,check)=>({type:'input_value',name,check}),body=name=>({type:'input_statement',name});
const statement=(type,message,args,colour=200,extensions=[])=>({type,message0:message,args0:args,previousStatement:null,nextStatement:null,colour,extensions});
const expression=(type,message,args,output,colour=120,extensions=[])=>({type,message0:message,args0:args,output,colour,extensions});
Blockly.defineBlocksWithJsonArray([
 {type:'az_start',message0:'Start program',nextStatement:null,colour:40},
 statement('az_press','press %1 threshold %2 → last_result',[dropdown('NAME','buttons'),num('THRESHOLD',.93,0,1)],200,['az_buttons_menu']),
 statement('az_wait','wait %1 seconds',[num('SECONDS',2)],210),
 statement('az_wait_button','wait for button %1 threshold %2 timeout %3 sec poll %4 sec → last_result',[dropdown('NAME','buttons'),num('THRESHOLD',.93,0,1),num('TIMEOUT',60,.1,3600),num('INTERVAL',2,.2,60)],210,['az_buttons_menu']),
 statement('az_wait_screen','wait for screen %1 threshold %2 timeout %3 sec poll %4 sec → last_result',[dropdown('NAME','screens'),num('THRESHOLD',.72,0,1),num('TIMEOUT',60,.1,3600),num('INTERVAL',2,.2,60)],210,['az_screens_menu']),
 statement('az_tap','tap native x %1 y %2',[num('X',0,0,16383,1),num('Y',0,0,16383,1)]),
 statement('az_if','if %1 then %2 else %3',[value('CONDITION','Boolean'),body('THEN'),body('ELSE')],35),
 statement('az_repeat','repeat %1 times %2',[num('COUNT',4,0,10000,1),body('BODY')],35),
 statement('az_while','while %1 time limit %2 seconds %3',[value('CONDITION','Boolean'),num('TIMEOUT',600,.1,86400),body('BODY')],35),
 statement('az_call','call program %1 → last_result',[dropdown('NAME','programs')],280,['az_programs_menu']),
 statement('az_set','set %1 to %2',[input('NAME','oil'),value('VALUE',null)],300),
 statement('az_read','read number %1 into %2',[dropdown('SOURCE','numbers'),input('NAME','oil')],300,['az_numbers_menu']),
 statement('az_return','return %1',[value('VALUE',null)],280),
 statement('az_log','log %1',[input('MESSAGE','Reached this step')],160),
 statement('az_fail','end with error %1',[input('MESSAGE','Expected button did not appear')],0),
 expression('az_number','%1',[num('VALUE',3000,-1e9,1e9)],'Number'),
 expression('az_bool','%1',[{type:'field_dropdown',name:'VALUE',options:[['true','true'],['false','false']]}],'Boolean'),
 expression('az_variable','value of %1',[input('NAME','last_result')],null,300),
 expression('az_compare','%1 %2 %3',[value('LEFT',null),{type:'field_dropdown',name:'TEST',options:[['>','>'],['>=','>='],['<','<'],['<=','<='],['=','=='],['≠','!=']]},value('RIGHT',null)],'Boolean'),
 expression('az_visible','button %1 visible at %2',[dropdown('NAME','buttons'),num('THRESHOLD',.93,0,1)],'Boolean',200,['az_buttons_menu']),
 expression('az_screen','screen %1 visible at %2',[dropdown('NAME','screens'),num('THRESHOLD',.72,0,1)],'Boolean',200,['az_screens_menu']),
 expression('az_not','not %1',[value('VALUE','Boolean')],'Boolean')
]);
const category=(name,colour,types)=>({kind:'category',name,colour,contents:types.map(type=>({kind:'block',type}))});
workspace=Blockly.inject('workspace',{toolbox:{kind:'categoryToolbox',contents:[category('Actions',200,['az_press','az_wait_button','az_wait_screen','az_tap','az_wait']),category('Flow',35,['az_if','az_repeat','az_while','az_call','az_return']),category('Values',120,['az_bool','az_number','az_variable','az_compare','az_not','az_visible','az_screen']),category('Data & logs',300,['az_set','az_read','az_log','az_fail'])]},media:'/vendor/blockly/media/',trashcan:true,scrollbars:true,sounds:false,zoom:{controls:true,wheel:true,startScale:.85,minScale:.35,maxScale:1.6}});
workspace.addChangeListener(event=>{if(!loading&&!event.isUiEvent&&event.type!==Blockly.Events.FINISHED_LOADING){dirty=true;el('message').textContent='Unsaved changes — Run uses the last saved version.';}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
function notice(text){el('message').textContent=text;}
async function api(action,payload={}){const response=await fetch('/api/programs/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Automaton-Control':'1'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function field(b,name){return b.getFieldValue(name);}
function chosen(b,name){const result=field(b,name);if(!result||result==='__missing__')throw Error('Choose an authored asset in '+b.type);return result;}
function needed(b,name){const child=b.getInputTargetBlock(name);if(!child)throw Error('Connect '+name+' on '+b.type);return child;}
function expr(b){switch(b.type){case 'az_number':return {op:'value',value:Number(field(b,'VALUE'))};case 'az_bool':return {op:'value',value:field(b,'VALUE')==='true'};case 'az_variable':return {op:'variable',name:field(b,'NAME')};case 'az_compare':return {op:'compare',test:field(b,'TEST'),left:expr(needed(b,'LEFT')),right:expr(needed(b,'RIGHT'))};case 'az_not':return {op:'not',value:expr(needed(b,'VALUE'))};case 'az_visible':return {op:'visible',button:chosen(b,'NAME'),threshold:Number(field(b,'THRESHOLD'))};case 'az_screen':return {op:'screen',name:chosen(b,'NAME'),threshold:Number(field(b,'THRESHOLD'))};default:throw Error('Not a value block: '+b.type);}}
function sequence(b){const nodes=[];for(;b;b=b.getNextBlock()){let n={id:b.id};const subtree=name=>sequence(b.getInputTargetBlock(name));switch(b.type){case 'az_press':n={...n,op:'press',button:chosen(b,'NAME'),threshold:Number(field(b,'THRESHOLD'))};break;case 'az_wait':n={...n,op:'wait',seconds:Number(field(b,'SECONDS'))};break;case 'az_wait_button':n={...n,op:'wait_button',button:chosen(b,'NAME'),threshold:Number(field(b,'THRESHOLD')),timeout:Number(field(b,'TIMEOUT')),interval:Number(field(b,'INTERVAL'))};break;case 'az_wait_screen':n={...n,op:'wait_screen',screen:chosen(b,'NAME'),threshold:Number(field(b,'THRESHOLD')),timeout:Number(field(b,'TIMEOUT')),interval:Number(field(b,'INTERVAL'))};break;case 'az_tap':n={...n,op:'tap',x:Number(field(b,'X')),y:Number(field(b,'Y'))};break;case 'az_if':n={...n,op:'if',condition:expr(needed(b,'CONDITION')),then:subtree('THEN'),else:subtree('ELSE')};break;case 'az_repeat':n={...n,op:'repeat',count:Number(field(b,'COUNT')),body:subtree('BODY')};break;case 'az_while':n={...n,op:'while',condition:expr(needed(b,'CONDITION')),timeout:Number(field(b,'TIMEOUT')),body:subtree('BODY')};break;case 'az_call':n={...n,op:'call',program:chosen(b,'NAME')};break;case 'az_set':n={...n,op:'set',variable:field(b,'NAME'),value:expr(needed(b,'VALUE'))};break;case 'az_read':n={...n,op:'read_number',source:chosen(b,'SOURCE'),variable:field(b,'NAME')};break;case 'az_return':n={...n,op:'return',value:expr(needed(b,'VALUE'))};break;case 'az_log':case 'az_fail':n={...n,op:b.type==='az_log'?'log':'fail',message:field(b,'MESSAGE')};break;default:throw Error('Unsupported statement '+b.type);}nodes.push(n);}return nodes;}
function documentData(){const tops=workspace.getTopBlocks(true);if(tops.length!==1||tops[0].type!=='az_start')throw Error('Connect all blocks to the single Start program block.');return {version:1,steps:sequence(tops[0].getNextBlock()),workspace:Blockly.serialization.workspaces.save(workspace)};}
const fieldKinds={az_press:['NAME','buttons'],az_wait_button:['NAME','buttons'],az_wait_screen:['NAME','screens'],az_visible:['NAME','buttons'],az_screen:['NAME','screens'],az_read:['SOURCE','numbers'],az_call:['NAME','programs']};
function rememberSelections(value){if(!value||typeof value!=='object')return;if(value.type&&fieldKinds[value.type]&&value.fields){const [name,kind]=fieldKinds[value.type],selected=value.fields[name];if(selected&&!menus[kind].some(option=>option[1]===selected))menus[kind].push(['Saved value: '+selected,selected]);}for(const child of Object.values(value))rememberSelections(child);}
function loadDocument(data,name,clean=true){if(!data.workspace)throw Error('This file has no visual workspace');rememberSelections(data.workspace);loading=true;Blockly.Events.disable();try{workspace.clear();Blockly.serialization.workspaces.load(data.workspace,workspace);el('name').value=name;loadedName=name;dirty=!clean;}finally{Blockly.Events.enable();loading=false;}if(clean)setTimeout(()=>{if(loadedName===name){dirty=false;notice('Loaded '+name);}},0);}
function reset(name='my_program'){loading=true;Blockly.Events.disable();try{workspace.clear();const start=workspace.newBlock('az_start');start.initSvg();start.render();start.moveBy(25,25);}finally{Blockly.Events.enable();loading=false;}el('name').value=name;loadedName=null;dirty=true;}
function discard(){return !dirty||window.confirm('Discard unsaved editor changes?');}
function refreshMenus(){for(const block of workspace.getAllBlocks(false)){const spec=fieldKinds[block.type];if(!spec)continue;const [name,kind]=spec,field=block.getField(name),current=field.getValue();field.setOptions(()=>menu(kind));if(menu(kind).some(option=>option[1]===current))field.setValue(current);}}
async function catalog(){const result=await api('catalog');const selected=el('saved').value;el('saved').replaceChildren();for(const name of result.names){const option=document.createElement('option');option.value=name;option.textContent=name;el('saved').append(option);}if(result.names.includes(selected))el('saved').value=selected;menus.programs=result.names.map(name=>[name,name]);for(const kind of ['buttons','screens','numbers'])menus[kind]=result[kind].filter(item=>item.templates.length).map(item=>[item.label,item.value]);refreshMenus();el('assets').textContent=JSON.stringify(result.targets,null,2);}
function attach(previous,type,fields={},inputs={}){const b=workspace.newBlock(type);for(const [name,value] of Object.entries(fields))b.setFieldValue(String(value),name);b.initSvg();for(const [name,child] of Object.entries(inputs))b.getInput(name).connection.connect(child.outputConnection||child.previousConnection);if(previous)previous.nextConnection.connect(b.previousConnection);b.render();return b;}
function leaf(type,fields){return attach(null,type,fields);}
function preferred(kind,name){const found=menus[kind].find(option=>option[1]===name||option[1].endsWith('/'+name));return found?found[1]:'__missing__';}
function example(kind){reset(kind==='farm'?'farm_4_8':kind==='oil'?'oil_supervisor':'demo_wait');loading=true;const start=workspace.getTopBlocks()[0];
 if(kind==='demo'){let b=attach(start,'az_log',{MESSAGE:'Demo started — no Android actions'});b=attach(b,'az_wait',{SECONDS:1});attach(b,'az_log',{MESSAGE:'Demo finished'});}
 if(kind==='farm'){const b=attach(start,'az_fail',{MESSAGE:'Author and test the 4-8 navigation before running this program.'});const press=attach(b,'az_press',{NAME:preferred('buttons','farm_start'),THRESHOLD:.93});const condition=leaf('az_variable',{NAME:'last_result'});const branch=attach(press,'az_if',{}, {CONDITION:condition});const wait=attach(null,'az_wait_button',{NAME:preferred('buttons','redo_sortie'),TIMEOUT:300,INTERVAL:2,THRESHOLD:.93});branch.getInput('THEN').connection.connect(wait.previousConnection);const fail=attach(null,'az_fail',{MESSAGE:'Farm start button not found'});branch.getInput('ELSE').connection.connect(fail.previousConnection);attach(wait,'az_return',{}, {VALUE:leaf('az_variable',{NAME:'last_result'})});}
 if(kind==='oil'){const read=attach(start,'az_read',{SOURCE:preferred('numbers','oil'),NAME:'oil'});const compare=leaf('az_compare',{TEST:'>'});compare.getInput('LEFT').connection.connect(leaf('az_variable',{NAME:'oil'}).outputConnection);compare.getInput('RIGHT').connection.connect(leaf('az_number',{VALUE:3000}).outputConnection);const branch=attach(read,'az_if',{}, {CONDITION:compare});const repeat=attach(null,'az_repeat',{COUNT:4});branch.getInput('THEN').connection.connect(repeat.previousConnection);const call=attach(null,'az_call',{NAME:preferred('programs','farm_4_8')});repeat.getInput('BODY').connection.connect(call.previousConnection);const check=attach(call,'az_if',{}, {CONDITION:leaf('az_not',{})});check.getInputTargetBlock('CONDITION').getInput('VALUE').connection.connect(leaf('az_variable',{NAME:'last_result'}).outputConnection);const fail=attach(null,'az_fail',{MESSAGE:'Farm program returned false'});check.getInput('THEN').connection.connect(fail.previousConnection);}
 loading=false;dirty=true;workspace.render();notice('Example loaded. Review and save it. Farm skeleton intentionally stops until you author it.');}
function bind(id,fn){el(id).onclick=async()=>{try{await fn();}catch(error){notice(error.message);}};}
bind('new',()=>{if(discard())reset();});bind('example-load',()=>{if(discard())example(el('example').value);});
bind('save',async()=>{const name=el('name').value;const result=await api('save',{name,program:documentData()});dirty=false;loadedName=name;notice(result.message);await catalog();});
bind('load',async()=>{if(discard()){const name=el('saved').value;loadDocument(await api('load',{name}),name);notice('Loaded '+name);}});
async function run(dry){if(dirty)throw Error('Save your changes before running.');if(loadedName!==el('name').value)throw Error('Save this program name first.');const result=await api('run',{name:loadedName,dry,max_seconds:Number(el('limit').value)*60});notice(result.message+(dry?' (simulation: no Android actions)':''));}
bind('run',()=>run(false));bind('dry',()=>run(true));bind('run-stop',async()=>notice((await api('stop')).message));
bind('export',()=>{const blob=new Blob([JSON.stringify(documentData(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=el('name').value+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
el('import').onchange=async event=>{try{if(!discard())return;const file=event.target.files[0];if(!file)return;if(file.size>400000)throw Error('File exceeds 400 KB');loadDocument(JSON.parse(await file.text()),file.name.replace(/\.json$/,''),false);notice('Imported into editor. Save to install.');}catch(error){notice(error.message);}finally{event.target.value='';}};
let polling=false;async function refresh(){if(polling)return;polling=true;try{const status=await api('status');el('state').textContent=(status.dry?'Dry run · ':'')+status.state;el('active').textContent=[status.name,status.program,status.error].filter(Boolean).join(' · ');el('variables').textContent=JSON.stringify(status.variables||{},null,2);el('events').textContent=(status.events||[]).join('\n');workspace.highlightBlock(!dirty&&loadedName===status.program?status.block:null);el('run').disabled=el('dry').disabled=status.state==='running'||status.state==='stopping';}catch(error){el('state').textContent='Connection unavailable';}finally{polling=false;}}
reset();catalog().catch(error=>notice(error.message));refresh();setInterval(refresh,1000);
})();
